export enum EActaStateKeys {
  ACTA_ALERT_STATE_KEY = 'ACTA_ALERT_STATE_KEY',
  APPLICATION_LANGUAGE = 'APPLICATION_LANGUAGE',
}

export enum EActaEventKeys {
  APPLICATION_MESSAGE = 'APPLICATION_MESSAGE',
}
