import BaseIcon from './BaseIcon'

export default function UpArrow() {
  return BaseIcon({
    alt: 'Up arrow',
    imgData:
      'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pjxzdmcgdmlld0JveD0iMCAwIDMyIDMyIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjx0aXRsZS8+PGcgZGF0YS1uYW1lPSJMYXllciAyIiBpZD0iTGF5ZXJfMiI+PHBhdGggZD0iTTEsMTZBMTUsMTUsMCwxLDEsMTYsMzEsMTUsMTUsMCwwLDEsMSwxNlptMiwwQTEzLDEzLDAsMSwwLDE2LDMsMTMsMTMsMCwwLDAsMywxNloiLz48cGF0aCBkPSJNMTAuNDEsMTkuODcsMTYsMTQuMjlsNS41OSw1LjU4YTEsMSwwLDAsMCwxLjQxLDBoMGExLDEsMCwwLDAsMC0xLjQxTDE2LjY0LDEyLjFhLjkxLjkxLDAsMCwwLTEuMjgsMEw5LDE4LjQ2YTEsMSwwLDAsMCwwLDEuNDFIOUExLDEsMCwwLDAsMTAuNDEsMTkuODdaIi8+PC9nPjwvc3ZnPg=='
  })
}
