export const ADD_SEARCH_PARAMS = "ADD_SEARCH_PARAMS"
export const SEARCH_SUCCESS = "SEARCH_SUCCESS"
export const SEARCH_FAILURE = "SEARCH_FAILURE"
export const FETCHING_BUS_SCHEDULE = "FETCHING_BUS_SCHEDULE"