export const SET_FETCHING = 'SET_FETCHING';
export const UNSET_FETCHING = 'UNSET_FETCHING';

export const GET_DEPARTURES_SUCCESS = 'GET_DEPARTURES_SUCCESS';
export const GET_DEPARTURES_FAILURE = 'GET_DEPARTURES_FAILURE';
