export const INITIATE_SEARCH = 'INITIATE_SEARCH'
export const INCOMPLETE_SEARCH = 'INCOMPLETE_SEARCH'
export const COMPLETED_SEARCH = 'COMPLETED_SEARCJ'
export const SEARCH_EXPIRED = 'INVALIDATE_REDDIT'
