// flow-typed signature: 8e3cce3fc9f10495009b41a96cfe9613
// flow-typed version: <<STUB>>/eslint-config-flowtype-essential_v^1.0.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-flowtype-essential'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-flowtype-essential' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-flowtype-essential/tests/fixtures/correct' {
  declare module.exports: any;
}

declare module 'eslint-config-flowtype-essential/tests/fixtures/incorrect' {
  declare module.exports: any;
}

declare module 'eslint-config-flowtype-essential/tests/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-flowtype-essential/index' {
  declare module.exports: $Exports<'eslint-config-flowtype-essential'>;
}
declare module 'eslint-config-flowtype-essential/index.js' {
  declare module.exports: $Exports<'eslint-config-flowtype-essential'>;
}
declare module 'eslint-config-flowtype-essential/tests/fixtures/correct.js' {
  declare module.exports: $Exports<'eslint-config-flowtype-essential/tests/fixtures/correct'>;
}
declare module 'eslint-config-flowtype-essential/tests/fixtures/incorrect.js' {
  declare module.exports: $Exports<'eslint-config-flowtype-essential/tests/fixtures/incorrect'>;
}
declare module 'eslint-config-flowtype-essential/tests/index.spec.js' {
  declare module.exports: $Exports<'eslint-config-flowtype-essential/tests/index.spec'>;
}
