// flow-typed signature: ad78f6a66ed0c3957ae07998fe92e41a
// flow-typed version: <<STUB>>/lodash-fp_v^0.10.4/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash-fp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash-fp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lodash-fp/convert' {
  declare module.exports: any;
}

declare module 'lodash-fp/lib/listing' {
  declare module.exports: any;
}

declare module 'lodash-fp/lib/mapping' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lodash-fp/convert.js' {
  declare module.exports: $Exports<'lodash-fp/convert'>;
}
declare module 'lodash-fp/index' {
  declare module.exports: $Exports<'lodash-fp'>;
}
declare module 'lodash-fp/index.js' {
  declare module.exports: $Exports<'lodash-fp'>;
}
declare module 'lodash-fp/lib/listing.js' {
  declare module.exports: $Exports<'lodash-fp/lib/listing'>;
}
declare module 'lodash-fp/lib/mapping.js' {
  declare module.exports: $Exports<'lodash-fp/lib/mapping'>;
}
