// flow-typed signature: 1f933f825f5117977c21b267b7963c5b
// flow-typed version: <<STUB>>/mui-downshift_v^1.2.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mui-downshift'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mui-downshift' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mui-downshift/dist/index' {
  declare module.exports: any;
}

declare module 'mui-downshift/dist/Input' {
  declare module.exports: any;
}

declare module 'mui-downshift/dist/Menu' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mui-downshift/dist/index.js' {
  declare module.exports: $Exports<'mui-downshift/dist/index'>;
}
declare module 'mui-downshift/dist/Input.js' {
  declare module.exports: $Exports<'mui-downshift/dist/Input'>;
}
declare module 'mui-downshift/dist/Menu.js' {
  declare module.exports: $Exports<'mui-downshift/dist/Menu'>;
}
