// flow-typed signature: 3fde36da641ed70ee494ad52c61a6bb4
// flow-typed version: <<STUB>>/redux-saga-request_v^0.1.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga-request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga-request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-saga-request/lib/request' {
  declare module.exports: any;
}

declare module 'redux-saga-request/request' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-saga-request/lib/request.js' {
  declare module.exports: $Exports<'redux-saga-request/lib/request'>;
}
declare module 'redux-saga-request/request.js' {
  declare module.exports: $Exports<'redux-saga-request/request'>;
}
