version: 2.1

orbs:
  node: circleci/node@4.7.0

workflows:
  ci:
    jobs:
      - node/run:
          name: Lint
          npm-run: lint
      - node/test:
          name: Test
      - node/run:
          name: Build
          npm-run: build
