const EN = {
  header: "Let's go to Osheaga!",
  on: 'departure date',
  day: 'August 2 2019',
  outboundDate: '2019-08-02',
  from: 'departing from',
  origin: 'dr5reg',
  nyc: 'New York',
  to: 'arriving to',
  mtl: 'Montreal',
  destination: 'f25dvk',
  departureTimeLabel: 'Departure Time',
  departureAddressLabel: 'Depature Address',
  arrivalTimeLabel: 'Arrival Time',
  arrivalAddressLabel: 'Arrival Address',
  travelTimeLabel: 'Travel Time',
  operatorLabel: 'Operator',
  priceLabel: 'Price',
}

const FR = {
  header: "Allons au festival d'Osheaga!",
  on: 'date de départ',
  day: '2 août 2019',
  outboundDate: '2019-08-02',
  from: 'au départ de',
  origin: 'dr5reg',
  nyc: 'New York',
  to: 'arriver à',
  mtl: 'Montréal',
  destination: 'f25dvk',
  departureTimeLabel: 'Heure de départ',
  departureAddressLabel: 'Adresse de départ',
  arrivalTimeLabel: 'Arrival Time',
  arrivalAddressLabel: 'Depature Address',
  travelTimeLabel: 'Temps de voyage',
  operatorLabel: 'Affaires',
  priceLabel: 'Prix',
}

export default { translations: { EN, FR } }
