const EN = {
  on: 'departure date',
  day: 'August 2 2019',
  outboundDate: '2019-08-02',
  from: 'departing from',
  origin: 'dr5reg',
  nyc: 'New York',
  to: 'arriving to',
  mtl: 'Montreal',
  destination: 'f25dvk',
  departureTimeLabel: 'Departure Time',
  departureAddressLabel: 'Departure Place',
  arrivalTimeLabel: 'Arrival Time',
  arrivalAddressLabel: 'Arrival Place',
  travelTimeLabel: 'Travel Time',
  operatorLabel: 'Operator',
  priceLabel: 'Price',
  minutesLabel: 'minutes',
  hoursLabel: 'hours',
}

const FR = {
  on: 'date de départ',
  day: '2 août 2019',
  outboundDate: '2019-08-02',
  from: 'au départ de',
  origin: 'dr5reg',
  nyc: 'New York',
  to: 'arriver à',
  mtl: 'Montréal',
  destination: 'f25dvk',
  departureTimeLabel: 'Heure de départ',
  departureAddressLabel: 'Lieu de départ',
  arrivalTimeLabel: "Heure d'arrivée",
  arrivalAddressLabel: "Lieu d'arrivée",
  travelTimeLabel: 'Temps de voyage',
  operatorLabel: 'Affaires',
  priceLabel: 'Prix',
  minutesLabel: 'minutes',
  hoursLabel: 'heures',
}

export default { translations: { EN, FR } }
