
export enum FETCH_VEHICLE_TYPES {
    FETCH_VEHICLES_REQUEST = "FETCH_VEHICLES_REQUEST",
    FETCH_VEHICLES_SUCCESS = "FETCH_FREENOW_VEHICLES_SUCCESS",
    FETCH_VEHICLES_FAILURE = "FETCH_VEHICLES_FAILURE",
    SET_VEHICLE_PAGE = "SET_VEHICLE_PAGE",
    SET_VEHICLE_SELECTED = "SET_VEHICLE_SELECTED"
  }