
export enum FETCH_DEPARTURE_TYPES {
    FETCH_DEPARTURES_REQUEST = "FETCH_DEPARTURES_REQUEST",
    FETCH_DEPARTURES_SUCCESS = "FETCH_DEPARTURES_SUCCESS",
    FETCH_EXTRA_DEPARTURES_SUCCESS = "FETCH_EXTRA_DEPARTURES_SUCCESS",
    FETCH_DEPARTURES_FAILURE = "FETCH_DEPARTURES_FAILURE"
  }