describe('Passenger Select', () => {
  it('Adds 1 Senior Passenger', () => {
    cy.visit('/')
    cy.getTestId('PASSENGER.TEXT')
      .find('button')
      .contains('1 passenger')
      .parent()
      .click()
    cy.getTestId('PASSENGER.DROP')
      .find('button')
      .getTestId('INCREMENT')
      .eq(2)
      .click()
  })

  it('Adds age to Senior 1', () => {
    cy.getTestId('AGE.SENIOR_AGES.0').siblings('button').click()
    cy.contains(60).click()
    cy.get('body').click()
  })
  it('Has 2 passengers added', () => {
    cy.getTestId('PASSENGER.TEXT').find('button').contains('2 passengers')
    cy.reload()
  })

  it('Adds 1 senior with Age of 60', () => {
    cy.getTestId('PASSENGER.TEXT')
      .find('button')
      .contains('1 passenger')
      .parent()
      .click()
    cy.getTestId('PASSENGER.DROP')
      .find('button')
      .getTestId('INCREMENT')
      .eq(2)
      .click()
    cy.getTestId('AGE.SENIOR_AGES.0').siblings('button').click()
    cy.contains(60).click()
    cy.get('body').click()
  })

  it('Adds 1 child Passenger with Age of 5', () => {
    cy.getTestId('PASSENGER.TEXT')
      .find('button')
      .contains('2 passenger')
      .parent()
      .click()
    cy.getTestId('PASSENGER.DROP')
      .find('button')
      .getTestId('INCREMENT')
      .eq(1)
      .click()
    cy.getTestId('AGE.CHILD_AGES.0').siblings('button').click()
    cy.contains(5).click()
    cy.get('body').click()
  })

  it('remove 1 adult and 1 child', () => {
    cy.getTestId('PASSENGER.TEXT')
      .find('button')
      .contains('3 passenger')
      .parent()
      .click()
    cy.getTestId('PASSENGER.DROP')
      .find('button')
      .getTestId('DECREMENT')
      .eq(0)
      .click()
    cy.getTestId('PASSENGER.DROP')
      .find('button')
      .getTestId('DECREMENT')
      .eq(1)
      .click()
  })
})
