export const LOCALES = ['en', 'fr'];

export const DEFAULT_LOCALE = 'en';

export const UPDATE_QUERY = '@@/App/UPDATE_QUERY';

export const FETCH_DEPARTURES = '@@/App/FETCH_DEPARTURES';

export const FETCH_DEPARTURES_SUCCESS = '@@/App/FETCH_DEPARTURES_SUCCESS';

export const FETCH_DEPARTURES_ERROR = '@@/App/FETCH_DEPARTURES_ERROR';

export const FETCH_DEPARTURES_COMPLETE = '@@/App/FETCH_DEPARTURES_COMPLETE';
