import * as departureActions from './departuresActions';

const rawData = {
  response: {
    departures: [
      {
        amenities: {
          display_name: '',
          wifi: true,
          toilet: true,
          ac: true,
          refreshment: false,
          food: false,
          hot_meal: false,
          power_outlets: true,
          tv: true,
          bus_attendant: false,
          leg_room: false,
          small_seat: false,
          average_seat: true,
          xl_seat: false,
          full_recline_seat: false,
        },
        arrival_timezone: 'America/Montreal',
        available_seats: 50,
        bus: null,
        busbud_departure_id: '4e58774b',
        class: 'Economy',
        class_name: '',
        complete: false,
        contractor_name: null,
        fare_name: null,
        deeplink: null,
        departure_timezone: 'America/New_York',
        departure_type: null,
        destination_location_id: 1938,
        duration: 640,
        has_search_details: true,
        has_bus_details: null,
        has_transfers: true,
        has_addons: null,
        id: 'NjgyMzcyZTE6NGU1ODc3NGI',
        links: {
          deeplink:
            'https://www.busbud.com/en/deeplink/dr5reg/f25dvk/NjgyMzcyZTE6NGU1ODc3NGI?outbound_date=2020-08-07&return_date&adults=1&children=0&seniors=0&child_ages=&senior_ages=&discount_code&utm_source={utm_source}&utm_campaign={utm_campaign}&utm_medium={utm_medium}',
        },
        num_transfers: null,
        operator_id: 'f450043c-d13d-4a9e-898b-964b74fa723a',
        origin_location_id: 53372,
        passenger_questions: [],
        schedule_id: null,
        sellable: true,
        source_id: 175,
        ticket_types: ['print'],
        departure_time: '2020-08-07T07:25:00',
        arrival_time: '2020-08-07T18:05:00',
        fetched_at: '2019-10-14T00:23:02.599Z',
        search_request_id:
          '2019101403595b09c543b9defb9f76bcf51ced5f6b21bc95d579cc9b16bb0218481949690022',
        unreliable_duration: null,
        has_unmapped_location: null,
        data_source: 'l2',
        cache_source: 'departure-service',
        prices: {
          currency: 'USD',
          total: 7650,
          categories: {
            adult: 7400,
            child: 7400,
            senior: 7400,
          },
          discount: 0,
          roundtrip_min: null,
          roundtrip_total: null,
          discounted: null,
          breakdown: {
            base: 7400,
            fees: 250,
            taxes: 0,
            discount: 0,
          },
        },
        trip_stops: [],
        addons: [],
        details: {
          num_transfers: 1,
        },
        terms: {
          type_of_id: 'photo_and_full_name',
          ticket_requirements: {
            print: 'printed_tkt',
            claim: 'printed_tkt',
          },
          nb_carry_on: 1,
          kg_by_carry_on: null,
          nb_checked_bags: 2,
          kg_by_bag: 23,
          checked_in_size_cm: null,
          extra_checked_in_fees: {
            type: 'per_extra_checked_in',
            amount: 1500,
          },
          nb_extra_checked_in: null,
          total_checked_in_kg: null,
          oversized_luggage: {
            allowed: true,
            allowed_types: ['bicycle', 'sport_equipment'],
            fees: {
              type: 'flat_fee',
              amount: 2000,
            },
            early_arrival_required: true,
            cover_required: true,
          },
          animals: {
            fees: {
              type: 'unknown',
              amount: null,
              percent: null,
            },
            main_compartment_allowed: false,
            hold_compartment_allowed: false,
            main_max_weight_kg: null,
            main_small_cage_required: null,
            hold_max_weight_kg: null,
            vaccination_required: true,
            special_animals_allowed: true,
            early_arrival_required: true,
            specific_hours: null,
          },
          refund_policies: [
            {
              type: 'no-refund',
              flat_fee: null,
              flat_fee_currency: null,
              percent_fee: null,
              cutoff_reference: 'departure-date',
              cutoff_from: null,
              cutoff_to: null,
              external_link: null,
            },
          ],
          refund: false,
          refund_cutoff: null,
          exchange_policies: [
            {
              type: 'no-exchange',
              flat_fee: null,
              flat_fee_currency: null,
              percent_fee: null,
              cutoff_reference: 'departure-date',
              cutoff_from: null,
              cutoff_to: null,
              external_link: null,
            },
          ],
          exchange: false,
          exchange_cutoff: null,
          currency: 'USD',
          addons: {},
          piece_of_id: true,
          boarding_requirement: 'printed_tkt',
          extra_bag_policy: true,
          extra_bag_cost: 1500,
          extra_bag_kg_cost: null,
          bag_allowed: true,
        },
      },
    ],
    operators: [
      {
        id: 'f450043c-d13d-4a9e-898b-964b74fa723a',
        source_id: 175,
        profile_id: 213,
        name: 'Adirondack Trailways',
        url: 'https://trailwaysny.com',
        logo_url:
          'https://busbud.imgix.net/operator-logos/logo_trailways.png?h={height}&w={width}&auto=format&fit=fill&bg=0FFF',
        display_name: 'Adirondack Trailways',
        review_state: 'good',
        sellable: true,
        fuzzy_prices: false,
        sell_tickets_cutoff: {
          minutes: 30,
        },
        amenities: {
          classes: {
            Normal: {
              display_name: '',
              wifi: true,
              toilet: true,
              ac: true,
              refreshment: false,
              food: false,
              hot_meal: false,
              power_outlets: true,
              tv: true,
              bus_attendant: false,
              leg_room: false,
              small_seat: false,
              average_seat: true,
              xl_seat: false,
              full_recline_seat: false,
            },
            Economy: {
              display_name: '',
              wifi: true,
              toilet: true,
              ac: true,
              refreshment: false,
              food: false,
              hot_meal: false,
              power_outlets: true,
              tv: true,
              bus_attendant: false,
              leg_room: false,
              small_seat: false,
              average_seat: true,
              xl_seat: false,
              full_recline_seat: false,
            },
          },
        },
        source: 'ny_trailways',
        referral_deal: false,
        display_url: 'trailwaysny.com',
        fraud_check: null,
      },
    ],
    locations: [
      {
        id: 53372,
        city_id: '375dd587-9001-acbd-84a4-683deda84183',
        name: 'Queens Village 219th St & Hillside Ave',
        address: [
          '88-1 219th St',
          'Queens Village',
          'NY 11427',
          'USA',
        ],
        type: 'bus_stop',
        lat: 40.729,
        lon: -73.745,
        geohash: 'dr5x9ykx8',
      },
      {
        id: 1938,
        city_id: '375dd587-9001-acbd-84a4-683dedfb933e',
        name: "Gare d'autocars",
        address: [
          '1717 Rue Berri',
          'Montr\u00e9al, QC H2L 4E9',
          'Canada',
        ],
        type: 'bus_station',
        lat: 45.516235,
        lon: -73.562668,
        geohash: 'f25dyjcr3',
      },
    ],
    complete: true,
  },
};

const formattedDepartures = [
  {
    id: 'NjgyMzcyZTE6NGU1ODc3NGI',
    operatorName: 'Adirondack Trailways',
    operatorLogo:
      'https://busbud.imgix.net/operator-logos/logo_trailways.png?h=200&w=200&auto=format&fit=fill&bg=0FFF',
    originLocationName: 'Queens Village 219th St & Hillside Ave',
    destinationLocationName: "Gare d'autocars",
    departureTime: '08/07/2020 7am EDT',
    departureSort: 1596799500000,
    arrivalTime: '08/07/2020 6pm EDT',
    priceDetail: 'USD 7650',
    wifi: true,
    toilet: true,
    ac: true,
    refreshment: false,
    tv: true,
    availableSeats: 50,
  },
];
describe('Departure Actions', () => {
  it('Poll action', () => {
    const index = 0;
    const expectedAction = {
      type: departureActions.POLL,
      index,
    };
    expect(departureActions.poll(index)).toEqual(expectedAction);
  });
  it('format success action', () => {
    const expectedAction = {
      type: departureActions.GET_DEPARTURES_SUCCEEDED,
      departures: formattedDepartures,
      complete: true,
    };
    expect(departureActions.fetchDeparturesSuccess(rawData)).toEqual(
      expectedAction,
    );
  });
});
