const CLEAR_SEARCH = 'search/CLEAR';

const GET_SEARCH = 'search/GET';
const GET_SEARCH_SUCCESS = 'search/GET/SUCCESS';
const GET_SEARCH_FAILURE = 'search/GET/FAILURE';

const GET_POLL_SUCCESS = 'poll/GET/SUCCESS';

const GET_CITY = 'city/GET';
const GET_CITY_SUCCESS = 'city/GET/SUCCESS';
const GET_CITY_FAILURE = 'city/GET/FAILURE';

export default {
    CLEAR_SEARCH,
    
    GET_SEARCH,
    GET_SEARCH_SUCCESS,
    GET_SEARCH_FAILURE,

    GET_POLL_SUCCESS,

    GET_CITY,
    GET_CITY_SUCCESS,
    GET_CITY_FAILURE,
};
